# cloudbuild.yaml
steps:
  # 1. Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/supple-serenity-458409-n0/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA",
        ".",
      ]
    # Use a larger machine type if the build needs more resources
    # machineType: 'E2_HIGHCPU_8'

  # 2. Push the image to Google Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/supple-serenity-458409-n0/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA",
      ]

  # 3. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [
        "run",
        "deploy",
        "${_SERVICE_NAME}", # Your Cloud Run service name
        "--image",
        "${_REGION}-docker.pkg.dev/supple-serenity-458409-n0/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--quiet", # Suppress interactive prompts
        # Reference secrets stored in Secret Manager
        # Replace <SECRET_NAME_IN_MANAGER> with the actual name in Secret Manager
        "--set-secrets=BOT_TOKEN=<YOUR_BOT_TOKEN_SECRET_NAME>:latest,ADMIN_USER_ID=<YOUR_ADMIN_ID_SECRET_NAME>:latest,FOOTER_TEXT=<YOUR_FOOTER_SECRET_NAME>:latest,WAIFU_API_URL=<YOUR_WAIFU_API_SECRET_NAME>:latest,GUILD_ID=<YOUR_GUILD_ID_SECRET_NAME>:latest",
        # Add other necessary flags like --cpu, --memory if needed
        # '--memory=512Mi',
        # '--cpu=1',
        # IMPORTANT: Ensure CPU is always allocated for a bot
        "--cpu-always-allocated",
        "--min-instances=1",
      ]

# Define substitutions (variables) used in the steps
substitutions:
  _REGION: "us-central1" # <<< REPLACE with your preferred region
  _REPO_NAME: "reddoor-bot" # <<< REPLACE with your Artifact Registry repo name
  _IMAGE_NAME: "reddoor-bot" # <<< REPLACE with your image name
  _SERVICE_NAME: "reddoor-bot-service" # <<< REPLACE with your Cloud Run service name
  # Add substitutions for your secret names if you prefer, e.g.
  # _BOT_TOKEN_SECRET_NAME: 'your-bot-token-secret'
  # Then use ${_BOT_TOKEN_SECRET_NAME} in the --set-secrets arg

# Specify the image to keep in the registry after the build
images:
  - "${_REGION}-docker.pkg.dev/supple-serenity-458409-n0/${_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA"
# Optional: Set build timeout
# timeout: 1200s
