services:
  red-door-bot:
    # image: red-door-bot
    build:
      context: .
      dockerfile: Dockerfile

    env_file: .env
    ports:
      # Some random port
      - "24000:24000"
    restart: unless-stopped
