name: discord_spam_bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dev_dependencies:
  lints: ^4.0.0
dependencies:
  collection: ^1.18.0
  cron: ^0.6.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  fpdart: ^1.1.0
  intl: ^0.19.0
  nyxx: ^6.2.1
  nyxx_commands: ^6.0.2
  riverpod: ^2.5.1
<<<<<<< Updated upstream
  web_socket_channel: ^3.0.1 # For Lavalink WebSocket connection
=======
  uuid: ^4.5.1
>>>>>>> Stashed changes
